  0%|          | 0/138 [00:00<?, ?it/s]
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [5, '5']
reward: 0.0
2025-07-11 14:02:09 - WARNING - latex2sympy2_extended.math_normalization - equations is deprecated, as it handled by the parser now
----------------------------------------------------------------------------------------------------

answer_parsed: [11, '11']
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [{6, 8*,*10}, '6, 8\\text{, }10']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [{6, 8*,*10}, '6, 8\\text{, }10']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [{6, 8*,*10}, '6, 8\\text{, }10']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [{6, 8*,*10}, '6, 8\\text{, }10']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [{6, 8*,*10}, '6, 8\\text{, }10']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [{6, 8*,*10}, '6, 8\\text{, }10']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [2/3, '\\frac{2}{3}']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [2/3, '\\frac{2}{3}']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [2/3, '\\frac{2}{3}']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [2/3, '\\frac{2}{3}']
reward: 0.0
2025-07-11 14:02:09 - WARNING - latex2sympy2_extended.math_normalization - equations is deprecated, as it handled by the parser now
----------------------------------------------------------------------------------------------------

answer_parsed: [1/12, '\\frac{1}{12}']
gold_parsed: [2/3, '\\frac{2}{3}']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [2/3, '\\frac{2}{3}']
reward: 0.0
2025-07-11 14:02:09 - WARNING - latex2sympy2_extended.math_normalization - equations is deprecated, as it handled by the parser now
----------------------------------------------------------------------------------------------------

answer_parsed: [240*x**7 - 1*17*x**6 + 7*x**5 + 19*x - 46, '240x^7 - 17x^6 + 7x^5 + 19x - 46']
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [5, '5']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [3, '3']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [3, '3']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [3, '3']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [3, '3']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [3, '3']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [3, '3']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [49, '49']
reward: 0.0
----------------------------------------------------------------------------------------------------

answer_parsed: []
gold_parsed: [49, '49']
reward: 0.0

accuracy rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
----------------------------------------------------------------------------------------------------

format rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
{'loss': 0.0, 'grad_norm': 15.871825218200684, 'learning_rate': 0.0, 'num_tokens': 25608.0, 'completions/mean_length': 128.0, 'completions/min_length': 128.0, 'completions/max_length': 128.0, 'completions/clipped_ratio': 1.0, 'completions/mean_terminated_length': 0.0, 'completions/min_terminated_length': 0.0, 'completions/max_terminated_length': 0.0, 'rewards/accuracy_reward/mean': 0.010416666977107525, 'rewards/accuracy_reward/std': 0.10206206142902374, 'rewards/format_reward/mean': 0.0, 'rewards/format_reward/std': 0.0, 'reward': 0.010416666977107525, 'reward_std': 0.025515519082546234, 'frac_reward_zero_std': 0.9375, 'kl': 0.0, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.02}
```python
from transformers import AutoModelForCausalLM

# Load original tied model
model = AutoModelForCausalLM.from_pretrained("google/gemma-2-2b-it", tie_word_embeddings=False)

# Set the randomly initialized lm_head to the previously tied embeddings
model.lm_head.weight.data = model.model.embed_tokens.weight.data.clone()

# Save the untied model
untied_model_dir = "dir/for/untied/model"
model.save_pretrained(untied_model_dir)
model.config.save_pretrained(untied_model_dir)

# Now use the original model but in untied format
model = AutoModelForCausalLM.from_pretrained(untied_model_dir)
```

  warnings.warn(
Traceback (most recent call last):
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/jcxy/haolu/workspace/frameworks/X-R1/src/x_r1/grpo.py", line 289, in <module>
    main(script_args, training_args, model_args )
  File "/data/jcxy/haolu/workspace/frameworks/X-R1/src/x_r1/grpo.py", line 253, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/transformers/trainer.py", line 3730, in training_step
    inputs = self._prepare_inputs(inputs)
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/trl/extras/profiling.py", line 96, in wrapper
    return func(self, *args, **kwargs)
  File "/data/jcxy/haolu/workspace/frameworks/X-R1/src/x_r1/x_grpo_trainer.py", line 1171, in _prepare_inputs
    generation_batch = self._generate_and_score_completions(generation_batch)
  File "/data/jcxy/haolu/workspace/frameworks/X-R1/src/x_r1/x_grpo_trainer.py", line 1204, in _generate_and_score_completions
    self._move_model_to_vllm()
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/trl/extras/profiling.py", line 96, in wrapper
    return func(self, *args, **kwargs)
  File "/data/jcxy/haolu/workspace/frameworks/X-R1/src/x_r1/x_grpo_trainer.py", line 1123, in _move_model_to_vllm
    self.vllm_client.update_named_param(name, param.data)
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/trl/extras/vllm_client.py", line 229, in update_named_param
    response = self.session.post(url, json={"name": name, "dtype": dtype, "shape": shape})
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
[rank0]:     response = self._make_request(
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 534, in _make_request
[rank0]:     response = conn.getresponse()
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connection.py", line 516, in getresponse
[rank0]:     httplib_response = super().getresponse()
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 1375, in getresponse
[rank0]:     response.begin()
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 318, in begin
[rank0]:     version, status, reason = self._read_status()
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 279, in _read_status
[rank0]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/socket.py", line 705, in readinto
[rank0]:     return self._sock.recv_into(b)
[rank0]: ConnectionResetError: [Errno 104] Connection reset by peer

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
[rank0]:     resp = conn.urlopen(
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
[rank0]:     retries = retries.increment(
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/util/retry.py", line 474, in increment
[rank0]:     raise reraise(type(error), error, _stacktrace)
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
[rank0]:     raise value.with_traceback(tb)
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
[rank0]:     response = self._make_request(
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connectionpool.py", line 534, in _make_request
[rank0]:     response = conn.getresponse()
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/urllib3/connection.py", line 516, in getresponse
[rank0]:     httplib_response = super().getresponse()
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 1375, in getresponse
[rank0]:     response.begin()
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 318, in begin
[rank0]:     version, status, reason = self._read_status()
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/http/client.py", line 279, in _read_status
[rank0]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/socket.py", line 705, in readinto
[rank0]:     return self._sock.recv_into(b)
[rank0]: urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/jcxy/haolu/workspace/frameworks/X-R1/src/x_r1/grpo.py", line 289, in <module>
[rank0]:     main(script_args, training_args, model_args )
[rank0]:   File "/data/jcxy/haolu/workspace/frameworks/X-R1/src/x_r1/grpo.py", line 253, in main
[rank0]:     train_result = trainer.train(resume_from_checkpoint=checkpoint)
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/transformers/trainer.py", line 2245, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/transformers/trainer.py", line 3730, in training_step
[rank0]:     inputs = self._prepare_inputs(inputs)
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/trl/extras/profiling.py", line 96, in wrapper
[rank0]:     return func(self, *args, **kwargs)
[rank0]:   File "/data/jcxy/haolu/workspace/frameworks/X-R1/src/x_r1/x_grpo_trainer.py", line 1171, in _prepare_inputs
[rank0]:     generation_batch = self._generate_and_score_completions(generation_batch)
[rank0]:   File "/data/jcxy/haolu/workspace/frameworks/X-R1/src/x_r1/x_grpo_trainer.py", line 1204, in _generate_and_score_completions
[rank0]:     self._move_model_to_vllm()
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/trl/extras/profiling.py", line 96, in wrapper
[rank0]:     return func(self, *args, **kwargs)
[rank0]:   File "/data/jcxy/haolu/workspace/frameworks/X-R1/src/x_r1/x_grpo_trainer.py", line 1123, in _move_model_to_vllm
[rank0]:     self.vllm_client.update_named_param(name, param.data)
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/trl/extras/vllm_client.py", line 229, in update_named_param
[rank0]:     response = self.session.post(url, json={"name": name, "dtype": dtype, "shape": shape})
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
[rank0]:     return self.request("POST", url, data=data, json=json, **kwargs)
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
[rank0]:     resp = self.send(prep, **send_kwargs)
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
[rank0]:     r = adapter.send(request, **kwargs)
[rank0]:   File "/data/jcxy/haolu/anaconda3/envs/haolu/lib/python3.10/site-packages/requests/adapters.py", line 682, in send
[rank0]:     raise ConnectionError(err, request=request)
[rank0]: requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
